version: '3.1'

services:
        upload:
                container_name: "upload"
                image: upload
                restart: always
                ports:
                        - 80:8080

                volumes:
                        - ./assets:/usr/src/app/resources/static/assets/uploads

volumes:
  db-data:
